#Faça um programa que leia uma frase pelo teclado 
# e mostre quantas vezes aparece a letra “A”, 
# em que posição ela aparece a primeira vez 
# e em que posição ela aparece a última vez.

fra = str(input('Digite uma frase: ')).upper().strip()
print('A letra A aparece {} vezes na frase.'.format(fra.count('A')))
print('A primeira letra A apareceu na posição {}'.format(fra.find('A')+1))
print('A última letra A apareceu na posição {}'.format(fra.rfind('A')+1))